#!/bin/bash
# Docker command for compiling the paper locally -- needs to be run with sudo access.
# For details, see: https://joss.readthedocs.io/en/latest/submitting.html 

docker run --rm \
    --volume $PWD:/data \
    --user $(id -u):$(id -g) \
    --env JOURNAL=joss \
    openjournals/inara
